name: CI

on:
  push:
    branches: [ demo ]
    paths-ignore:
      - '**/*.md'

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: testuser
          MONGO_INITDB_ROOT_PASSWORD: testpass
        options: >-
          --health-cmd="mongosh --username testuser --password testpass --eval 'db.runCommand({ ping: 1 })' --quiet"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MONGO_HOST: "mongodb://testuser:testpass@localhost:27017"

    steps:
      - uses: actions/checkout@v4

      - name: Wait for MongoDB
        run: |
          for i in {1..10}; do
            echo "Attempt $i: trying to ping MongoDB at $MONGO_HOST"
            if mongosh "$MONGO_HOST" --eval 'db.runCommand({ ping: 1 })'; then
              echo "✅ MongoDB is up!"
              break
            fi
            echo "Waiting for MongoDB..."
            sleep 3
          done

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run integration tests
        run: |
          source venv/bin/activate
          pytest tests/integration